# Generated by Django 6.0.5 on 2026-05-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_title', models.CharField(max_length=100)),
                ('ser_data', models.TextField()),
            ],
        ),
    ]
