# Generated by Django 6.0.5 on 2026-05-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab_title', models.CharField(max_length=100)),
                ('ab_data', models.TextField()),
            ],
        ),
    ]
